name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger the workflow only for tags that follow the pattern 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install PDM
      - name: Install PDM
        run: python -m pip install --upgrade pip
      - name: Install pdm
        run: pip install pdm

      # Install dependencies
      - name: Install dependencies
        run: pdm install

      # Build the package
      - name: Build the package
        run: pdm build

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*

