name: Run PDM Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install PDM
      - name: Install PDM
        run: python -m pip install --upgrade pip
      - name: Install pdm
        run: pip install pdm

      # Install dependencies
      - name: Install dependencies
        run: pdm install

      # Run tests
      - name: Run PDM tests
        run: pdm test
